added ls la into netlify yml

diff --git a/.github/workflows/netlify.yml b/.github/workflows/netlify.yml
--- a/.github/workflows/netlify.yml
+++ b/.github/workflows/netlify.yml
@@ -13,6 +13,11 @@ jobs:
         run: |
           bun i
           bun run build
+      - name: 🔍 Check output after build
+        run: |
+          ls -la
+          ls -la netlify/functions || echo "functions directory missing!"
+
       - name: Deploy to Netlify
         uses: nwtgck/actions-netlify@v3.0
         with:
